name: authentication_repository
description: Authentication repository package
version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  uuid: ^4.5.2
